import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import fetchHandler from "../utils/fetchHandler";
import { Box, Button, Container, Heading } from "@chakra-ui/react";
import Hero from "@/components/Hero/Hero";
import AboutTeam from "@/components/AboutTeam/AboutTeam";

export default function Home() {
  const [user, setUser] = useState({});

  const getProfile = async () => {
    try {
      const response = await fetchHandler.get("/api/profile/get");
      setUser(response.data.profile);
    } catch (error) {
      console.log("NOT LOGGED IN");
    }
  };

  useEffect(() => {
    getProfile();
  }, []);

  return (
    <>
      <Head>
        <title>Mockland | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/MocklandLogo.ico" />
      </Head>
      <main>
        <Hero />
        <AboutTeam />
      </main>
    </>
  );
}
