import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import fetchHandler from "../utils/fetchHandler";

export default function Home() {
  const [user, setUser] = useState({});

  const getProfile = async () => {
    const response = await fetchHandler.get("/api/profile/get");
    setUser(response.data.profile);
    console.log("response", response);
  };

  useEffect(() => {
    getProfile();
  }, []);

  return (
    <>
      <Head>
        <title>Mockland | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Mockland</h1>
        {user && (
          <h2>
            {user.firstName} {user.lastName}
          </h2>
        )}
        <div>CONNECTED TO FLY</div>
        <ul>
          <li>
            <Link href="/mocks">Mocks</Link>
          </li>
          <li>
            <Link href="/auth/login">Login</Link>
          </li>
          <li>
            <Link href="/auth/register">Register</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
